project:
  type: website
  output-dir: docs

website:
  title: "Sardinia Sailing Holidays"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: What to pack
      - href: itinerary.qmd
        text: Itinerary
      - href: Page3.qmd
        text: Just a random task

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



